### PR TITLE
Fix glTF / glb root node transform

### PR DESCRIPTION
**Pull request by iche033**
# 🦟 Bug fix

## Summary

There is a long standing issue in assimp on models having incorrect rotations: https://github.com/assimp/assimp/issues/849.

Currently, our assimp loader drops the root node transform (setting it to identity) to work around the issue. However, this caused other assets's rotation to be appear incorrect and inconsistent with other rendering / modeling tools. This PR adapts a another workaround posted in https://github.com/assimp/assimp/issues/849 to fix the root node transform for glTF / glb meshes.

Update as of [40c7bbb](https://github.com/gazebosim/gz-common/pull/543/commits/40c7bbbb0b3231f03888a6413e25a500511cc12c) - Changes should how only affect glTF / glb and kept the same behavior for other file formats like dae.

Here are tests with a couple of glb meshes in gazebo and other tools. The camera in Gazebo is set up to have the same orientation as the these tools (Y up, facing -X)

[WaterBottle](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/WaterBottle)

Gazebo Before (ignore the black seam at the front, it's clipped by camera's near clip plane):
WaterBottle_before

Gazebo After (pay attention to logo on the bottle):
WaterBottle_after

three.js editor:

WaterBottle_threejs_editor

godot:
WaterBottle_godot

[BarramundiFish](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BarramundiFish):

Gazebo Before:
BarramundiFish_before

Gazebo After:
BarramundiFish_after

three.js editor:
BarramundiFish_threejs_editor

godot:
BarramundiFish_godot

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by iche033** [comment]
@luca-della-vedova do you still remember the meshes that you were having the rotation issue with?  I should probably also test them to make sure they still work

**Comment by luca-della-vedova** [comment]
> @luca-della-vedova do you still remember the meshes that you were having the rotation issue with? I should probably also test them to make sure they still work

Very interesting, thanks for the fix!
I believe the issue was actually not found on glb models but on other extensions, I can't remember the details but I believe one of the meshes that gave us the most trouble was the [walking actor](https://app.gazebosim.org/Mingfei/fuel/models/actor) (collada)

**Comment by iche033** [comment]
> can we add a test to `UpdatedRootNodeTransform` ?

After testing with different glb meshes, I found that most of the code from the workaround is actually not needed so I simplified the fix quite a bit in [8b0d752](https://github.com/gazebosim/gz-common/pull/543/commits/8b0d752043fb6ab3e62548c026c035e0665fe041). The current AssimpLoader tests has code to load glTF / glb meshes and should now cover all of the the new code ([coverage](https://app.codecov.io/gh/gazebosim/gz-common/pull/543?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=gazebosim#diff-Z3JhcGhpY3Mvc3JjL0Fzc2ltcExvYWRlci5jYw==)).

**Comment by iche033** [comment]
> I believe the issue was actually not found on glb models but on other extensions

ah ok I see! The changes in this PR should only affect glTF / glb meshes and not daes so I think we should be fine here.

**Comment by iche033** [comment]
added one more test to verify that the glb mesh's vertices are correct. [9b533c8](https://github.com/gazebosim/gz-common/pull/543/commits/9b533c88703ae186d35054b2589ff9b6f00c060b)

**Review by mjcarroll — APPROVED** [review]

**Review by ahcorde — APPROVED** [review]

**Pull request merged**
