### PR TITLE
Fixed MeshManager Singleton

### PR DESCRIPTION
**Pull request by ahcorde**
Signed-off-by: ahcorde <ahcorde@gmail.com>

# 🦟 Bug fix

## Summary

Related with https://github.com/gazebosim/gz-sim/issues/1725

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by mjcarroll** [comment]
I think that this breaks ABI, unfortunately (removing the base class).

**Comment by ahcorde** [comment]
> I think that this breaks ABI, unfortunately (removing the base class).

ABi checker is failiing beacuse of a cpp flag

```bash
WARNING: version number #2 is not set (use --v2=NUM option)
warning: command line option -std=c++17 is valid for C++/ObjC++ but not for C
```

**Comment by azeey** [comment]
Ah, the `~SingletonT` destructor is virtual, so this might actually be breaking ABI. Can we just overload `Instance` without removing the inheritance?

**Comment by iche033** [comment]
rebuilt with this branch and confirmed that rotate tool works for me now

**Review by iche033 — APPROVED** [review]

**Pull request merged**
