### PR TITLE
Merge ign-common3 ➡️  ign-common4

### PR DESCRIPTION
**Pull request by azeey**
# ➡️  Forward port

Port `ign-common3 ` ➡️  `ign-common4`

Branch comparison: https://github.com/gazebosim/gz-common/compare/ign-common4...ign-common3

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

### CODE REVIEW

**Review by mjcarroll — APPROVED** [review]

**Comment by azeey** [comment]
@osrf-jenkins run tests please

**Comment by azeey** [comment]
Included https://github.com/gazebosim/gz-common/pull/561 to fix test failures.

**Comment by azeey** [comment]
@osrf-jenkins run tests please

**Comment by mjcarroll** [comment]
Windows build is a test that is timing-sensitive, homebrew is an existing deprecation message (we could consider disabling it). 

 So this is actually green.

**Pull request merged**
