### PR TITLE
Fix build error when using gz:: with ign-common4

### PR DESCRIPTION
**Pull request by scpeters**
# 🦟 Bug fix

Fixes a build error

## Summary

This doesn't yet fix the build error; it just illustrates it with some example code that fails to compile.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by mjcarroll** [comment]
The issue here is that all of the headers in the `gz` folder still have the `ignition` namespace, when they should actually be in the `gz` namespace.  I will PR to address this.  It may have been an oversite, or the result of a bad merge?

**Comment by scpeters** [comment]
I think the `gz/common/config.hh.in` is missing something:

* https://github.com/gazebosim/gz-math/blob/ign-math6/include/gz/math/config.hh.in#L19-L26
* https://github.com/gazebosim/gz-common/blob/ign-common4/include/gz/common/config.hh.in

**Comment by mjcarroll** [comment]
> I think the gz/common/config.hh.in is missing something:


Added in [6f5c2ed](https://github.com/gazebosim/gz-common/pull/489/commits/6f5c2edaa1aa71a4998ad87c06f37a7289c0cef5)

**Comment by scpeters** [comment]
> > I think the gz/common/config.hh.in is missing something:
> 
> Added in [6f5c2ed](https://github.com/gazebosim/gz-common/pull/489/commits/6f5c2edaa1aa71a4998ad87c06f37a7289c0cef5)

thanks!

**Review by mjcarroll — APPROVED** [review]

**Review by azeey — APPROVED** [review]
LGTM! My only question is: do we need to do the same for the headers in the components of gz-common?

**Comment by mjcarroll** [comment]
> do we need to do the same for the headers in the components of gz-common?

Likely yes, I will go ahead and do that.  It may make sense to switch the tests to go ahead and use the `gz` namespace to guarantee that this is actually getting exercised, but I'm going to leave that to a follow-up.

**Review by azeey — APPROVED** [review]

**Pull request merged**
