### PR TITLE
Feature: Inits units tests for fbx and glTF2

### PR DESCRIPTION
**Pull request by onurtore**
AssimpLoader_TEST.cc updated to include basic unit tests for fbx and glb mesh files. New mesh files uploaded.

### CODE REVIEW

**Comment by onurtore** [comment]
@luca-della-vedova

**Review by ahcorde — CHANGES_REQUESTED** [review]
conflicts

**Comment by luca-della-vedova** [comment]
CI will complain even if your tests fail because of the missing `assimp` dependency. I guess can just ping here when they are passing and this is ready for review?

**Comment by luca-della-vedova** [comment]
Merging first, will fix the tests on the main branch

**Pull request merged**
