### PR TITLE
Fix: Works when the root node doesnt have child

### PR DESCRIPTION
**Pull request by onurtore**
Previous version does not work if root node does not have a child (creates problems for simple meshes like avocado below.)

### CODE REVIEW

**Comment by onurtore** [comment]
@luca-della-vedova

**Comment by luca-della-vedova** [comment]
Thanks! Can you share a model (preferably on fuel) where this behavior happens?

**Comment by onurtore** [comment]
Hi,
Didnt have the change to check on the fuel, but I will do:
[Avocado.zip](https://github.com/gazebosim/gz-common/files/8751576/Avocado.zip)

**Comment by luca-della-vedova** [comment]
Thanks! Can you sign off the commit and force-push to fix the DCO erro?

**Comment by onurtore** [comment]
@luca-della-vedova  done

**Review by luca-della-vedova — APPROVED** [review]
I'm OK with merging but not sure why DCO is failing :shrug:

**Comment by onurtore** [comment]
@luca-della-vedova , I can rebase branch as the checks mentioned, however it looks to me that my commit already fullfill the requirement. Do you want me to anything?

**Pull request merged**
