### PR TITLE
Default name assignment to animations without names

### PR DESCRIPTION
**Pull request by onurtore**
# 🦟 Bug fix

Related to #393 

## Summary

Current implementation for the assimp loader does not check the names of the animations loaded through assimp. This PR adds default names for the animations without names. This approach is similar to how ColladaLoader names the animations.

## Checklist
- [X] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

### CODE REVIEW

**Comment by mjcarroll** [comment]
The macOS warning here is due to an ffmpeg update and can be ignored.

**Comment by onurtore** [comment]
@Ahcorde, 
What I can do CI/CD, it looks failure reason doesnt comes from my code?

**Comment by mjcarroll** [comment]
> What I can do for CI/CD, it looks failure reason doesnt comes from my code?

I agree, the GDAL errors are not because of this PR.  With approval, we can go ahead and merge here.

**Comment by mjcarroll** [comment]
Is the intention to still to target this to `main`, or should it target `gz-common5` ?

**Comment by mjcarroll** [comment]
ABI checker likely to fail until there is some release from `main`, so this is good to go.

**Review by mjcarroll — APPROVED** [review]

**Pull request merged**
