### PR TITLE
Avoid Io.hh header name clash

### PR DESCRIPTION
**Pull request by hidmic**
# 🦟 Bug fix

Fixes https://github.com/gazebosim/gz-common/issues/470.

## Summary

More of a hunch than a fix. I suspect neither Mac OS nor Windows do case sensitive header look up, which creates a clash between the `Io.hh` file and the generated `io.hh` file.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by mjcarroll** [comment]
Yep, this is very likely the fix.

**Review by mjcarroll — APPROVED** [review]

**Comment by hidmic** [comment]
Would you mind releasing this @mjcarroll ?

**Comment by mjcarroll** [comment]
Ah yeah, in order for it to be released, we need to target something other than `main`.  Can this land on garden?

**Comment by scpeters** [comment]
an alternative is to nest the headers of components in a subfolder like `gz/common/io/Io.hh`

**Comment by hidmic** [comment]
There was no fundamental reason to name that header `Io.hh`, so no biggie.

**Pull request merged**
