### PR TITLE
Remove configure.bat, export CXX_STANDARD

### PR DESCRIPTION
**Pull request by scpeters**
# 🦟 Bug fix

Testing a fix for https://github.com/gazebosim/gz-common/issues/386 using the matching branch name of https://github.com/gazebosim/gz-cmake/pull/271

## Summary

I needed to make a change in order to test the fix for #386 and it's safe to remove `configure.bat` on any branches not used by gazebo11's CI, so I'm doing so here.

## Checklist
- [X] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by scpeters** [comment]
Success! https://build.osrfoundation.org/job/ign_common-pr-win/487/testReport/(root)/VideoEncoderTest/

**Comment by chapulina** [comment]
@osrf-jenkins run tests please now that https://github.com/gazebosim/gz-cmake/pull/271 has been merged

**Comment by scpeters** [comment]
the windows build failed due to the matching gazebodistro branch name, so I deleted that branch and am retrying the build

**Comment by scpeters** [comment]
I believe the examples were failing to compile because the core library doesn't export a CXX_STANDARD; I've fixed this in https://github.com/gazebosim/gz-common/pull/387/commits/0ca090651d05e2a7e3e5f55ad25c6315e6f3575f

**Comment by scpeters** [comment]
compiler warnings will be fixed in #377

**Comment by scpeters** [comment]
> compiler warnings will be fixed in #377

warnings fixed in https://github.com/gazebosim/gz-common/pull/387/commits/c58b3923b4677cb4240d6e58bf79b67b187746a6

**Comment by scpeters** [comment]
> > compiler warnings will be fixed in #377
> 
> warnings fixed in [c58b392](https://github.com/gazebosim/gz-common/commit/c58b3923b4677cb4240d6e58bf79b67b187746a6)

rebuilding math7 nightly debs...

**Review by chapulina — APPROVED** [review]

**Pull request merged**
